### ISSUE TITLE
Meta Data for Good relative wealth index

### ISSUE THREAD

**Issue by abhidg** [kraemer-lab/DART-Pipeline#70]
- [x] Ensure methodology is the same as Meta's for aggregation:  https://dataforgood.facebook.com/dfg/docs/tutorial-calculating-population-weighted-relative-wealth-index
- [x] Ideally using worldpop density data, check with @prathyushsambaturu if this is feasible (Meta's link uses meta's pop density which is not used elsewhere in the pipeline)
- [x] Change metric name to `meta.relative_wealth_index`
- [x] Update metrics.toml if required
- [x] Use column names from GADM instead of admin_*, specifically, NAME_x and GID_x where x=1,2.
- [x] Drop resolution column

**Comment by rowannicholls** [comment]
@abhidg 
- I am currently calling the metric `population_weighted.relative_wealth_index`, do you still want to rename it to `meta.relative_wealth_index`?
- `metrics.toml` currently has the following, does it need updating?

```
[meta.relative_wealth_index]
description = "Relative wealth index"
units = "unitless"
statistics = ["mean"]
license = "CC-BY-4.0"
url = "https://data.humdata.org/dataset/relative-wealth-index"
```

**Comment by rowannicholls** [comment]
- The column names have been changed
- The resolution column has been dropped
- Metric name changed to `meta.relative_wealth_index`

Sub-pipelines affected:

```
geospatial/aphrodite-daily-mean-temp
geospatial/aphrodite-daily-precip
geospatial/era5-reanalysis
geospatial/worldpop-count
geospatial/worldpop-density

meta/relative-wealth-index

meteorological/aphrodite-daily-mean-temp
meteorological/aphrodite-daily-precip
meteorological/era5-reanalysis

sociodemographic/worldpop-count
sociodemographic/worldpop-density
```
